In [1]:
import pandas as pd

In [2]:
city = pd.read_csv(r"C:\Users\eymem\Documents\GitHub\Population-Diversity-Study\city.csv")

In [3]:
city.head()

   ID            Name CountryCode       District  Population
0   1           Kabul         AFG          Kabol     1780000
1   2        Qandahar         AFG       Qandahar      237500
2   3           Herat         AFG          Herat      186800
3   4  Mazar-e-Sharif         AFG          Balkh      127800
4   5       Amsterdam         NLD  Noord-Holland      731200

In [4]:
city.shape

(4079, 5)

In [5]:
city.dtypes

ID              int64
Name           object
CountryCode    object
District       object
Population      int64
dtype: object

In [6]:
city["Population"].describe()

count    4.079000e+03
mean     3.504682e+05
std      7.237757e+05
min      4.200000e+01
25%      1.147890e+05
50%      1.670510e+05
75%      3.106385e+05
max      1.050000e+07
Name: Population, dtype: float64

In [7]:
city.isna().sum()

ID             0
Name           0
CountryCode    0
District       4
Population     0
dtype: int64

In [8]:
city.dropna(subset=['District'])

        ID            Name CountryCode       District  Population
0        1           Kabul         AFG          Kabol     1780000
1        2        Qandahar         AFG       Qandahar      237500
2        3           Herat         AFG          Herat      186800
3        4  Mazar-e-Sharif         AFG          Balkh      127800
4        5       Amsterdam         NLD  Noord-Holland      731200
...    ...             ...         ...            ...         ...
4074  4075      Khan Yunis         PSE     Khan Yunis      123175
4075  4076          Hebron         PSE         Hebron      119401
4076  4077        Jabaliya         PSE     North Gaza      113901
4077  4078          Nablus         PSE         Nablus      100231
4078  4079           Rafah         PSE          Rafah       92020

[4075 rows x 5 columns]

In [9]:
city.duplicated().sum()

np.int64(0)

In [10]:
city.rename(columns={"ID": "CityID", "Name": "City"}, errors="ignore", inplace=True)

In [11]:
city["City"].value_counts().sort_values(ascending=False)

City
San Jose        3
San Fernando    3
León            3
Toledo          3
Richmond        3
               ..
Hebron          1
Jabaliya        1
Nablus          1
Kabul           1
Cumaná          1
Name: count, Length: 4001, dtype: int64

In [12]:
city["CountryCode"].value_counts().sort_values(ascending=False)

CountryCode
CHN    363
IND    341
USA    274
BRA    250
JPN    248
      ...
URY      1
NCL      1
VUT      1
WLF      1
VIR      1
Name: count, Length: 232, dtype: int64

In [13]:
city["District"].value_counts().sort_values(ascending=False)

District
England         71
São Paulo       69
California      68
Punjab          47
West Bengali    46
                ..
Béjaïa           1
Mostaganem       1
Tébessa          1
Tlemcen          1
Béchar           1
Name: count, Length: 1366, dtype: int64

In [14]:
city["District"].value_counts().sort_values(ascending=False)

District
England         71
São Paulo       69
California      68
Punjab          47
West Bengali    46
                ..
Béjaïa           1
Mostaganem       1
Tébessa          1
Tlemcen          1
Béchar           1
Name: count, Length: 1366, dtype: int64

In [15]:
city_sql = city.to_csv(r"C:\Users\eymem\Documents\GitHub\Population-Diversity-Study\city_sql.csv",index=False)

In [16]:
city.head()

   CityID            City CountryCode       District  Population
0       1           Kabul         AFG          Kabol     1780000
1       2        Qandahar         AFG       Qandahar      237500
2       3           Herat         AFG          Herat      186800
3       4  Mazar-e-Sharif         AFG          Balkh      127800
4       5       Amsterdam         NLD  Noord-Holland      731200